const colorConstants = {
    CORRECT_ANSWER_BORDER_COLOR: 'green',
    INCORRECT_ANSWER_BORDER_COLOR: 'red',
    ADMIN_PREVIEW_USER_SELECTED_ANSWER_BACKGROUND_COLOR: '#81cdff',
    ADMIN_PREVIEW_NOT_SELECTED_ANSWER_BACKGROUND_COLOR: '#e0e0e0',
}
export default colorConstants
