export const SETTINGS_KEYS = {
    DEFAULT_QUESTION_DURATION: `DEFAULT_QUESTION_DURATION`,
    DEFAULT_CORRECT_ANSWER_POINTS: 'DEFAULT_CORRECT_ANSWER_POINTS',
    DEFAULT_INCORRECT_ANSWER_POINTS: 'DEFAULT_INCORRECT_ANSWER_POINTS',
}
