import { DefaultMetadataTitle, DefaultMetadataDescription } from '@/app/constants'

// This is automatically generated by next.js because of not-found page

export const metadata = {
  title: DefaultMetadataTitle,
  description: DefaultMetadataDescription,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
