import {
    DefaultMetadataTitle,
    DefaultMetadataDescription,
} from '@/app/constants'

// This is automatically generated by next.js because of not-found page

export const metadata = {
    title: DefaultMetadataTitle,
    description: DefaultMetadataDescription,
    icons: {
        icon: [
            { url: '/favicon.ico', sizes: 'any' },
            { url: '/termodom_logo.svg', type: 'image/svg+xml' },
        ],
        apple: '/Termodom_Logo.png',
    },
    openGraph: {
        title: DefaultMetadataTitle,
        description: DefaultMetadataDescription,
        images: [
            {
                url: 'https://www.termodom.rs/Termodom_Logo.png',
                width: 500,
                height: 500,
                alt: 'Termodom Logo',
            },
        ],
        siteName: DefaultMetadataTitle,
    },
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
