// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateLog(ctx context.Context, arg CreateLogParams) (Log, error)
	ListLogs(ctx context.Context, arg ListLogsParams) ([]Log, error)
}

var _ Querier = (*Queries)(nil)
