delete from "Cities" where "Name" in ('Beograd - Čukarica',
	'Beograd - Novi Beograd',
	'Beograd - Palilula',
	'Beograd - Rakovica',
	'Beograd - Savski Venac',
	'Beograd - Stari grad',
	'Beograd - Voždovac',
	'Beograd - Zemun',
	'Beograd - Zvezdara',
	'Beograd - Barajevo',
	'Beograd - Grocka',
	'Beograd - Lazarevac',
	'Beograd - Mladenovac',
	'Beograd - Obrenovac',
	'Beograd - Sopot',
	'Beograd - Surčin',
	'Beograd - Ostalo',
	'Novi Sad - Futog',
	'Novi Sad - Veternik',
	'Novi Sad - Begeč',
	'Novi Sad - Kisač',
	'Novi Sad - Rumenka',
	'Novi Sad - Stepanovićevo',
	'Novi Sad - Kać',
	'Novi Sad - Čenej',
	'Novi Sad - Budisava',
	'Novi Sad - Kovilj',
	'Novi Sad - Ostalo',
	'Niš - Medijana',
	'Niš - Palilula',
	'Niš - Pantelej',
	'Niš - Crveni krst',
	'Niš - Niška banja',
	'Niš - Ostalo',
	'Kragujevac - Aerodrom',
	'Kragujevac - Pivara',
	'Kragujevac - Stanovo',
	'Kragujevac - Stari grad',
	'Kragujevac - Stragari',
	'Kragujevac - Ostalo',
	'Subotica',
	'Zrenjanin',
	'Pančevo',
	'Čačak',
	'Novi Pazar',
	'Kraljevo',
	'Kruševac',
	'Jagodina',
	'Sremska Mitrovica',
	'Ruma',
	'Šabac',
	'Smederevo',
	'Bela crkva',
	'Kula',
	'Beograd - Resnik'
)