DELETE FROM "Settings" WHERE "Key" = 'FEATURE_CRON_AZURIRAJ_NIVO_NEAKTIVNIM_KORISNICIMA';
DELETE FROM "Settings" WHERE "Key" = 'AZURIRAJ_NIVO_NEAKTIVNIM_KORISNICIMA_NEAKTIVAN_JE_AKO_NIJE_KUPOVAO_DANA';
DELETE FROM "Settings" WHERE "Key" = 'AZURIRAJ_NIVO_NEAKTIVNIM_KORISNICIMA_DESTINACIONI_NIVO';