namespace TD.Office.Common.Contracts.Enums;

public enum SettingKey
{
	OTVARANJE_PARTNERA_BAZA,
	PARTNERI_PO_GODINAMA_KOMERCIJALNO_FINANSIJSKO_PERIOD_GODINA,
	PARTNERI_PO_GODINAMA_DEFAULT_TOLERANCIJA,
	PARTNER_ANALIZA_GODINA_UNAZAD
}
