// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Log struct {
	ID         uuid.UUID       `json:"id"`
	EntityID   int64           `json:"entity_id"`
	EntityType string          `json:"entity_type"`
	ActionType string          `json:"action_type"`
	New        json.RawMessage `json:"new"`
	Old        json.RawMessage `json:"old"`
	CreatedBy  int32           `json:"created_by"`
	CreatedAt  time.Time       `json:"created_at"`
}
