// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"
	"time"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs (
    entity_id, entity_type, action_type, new, old,logged_by, created_by, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, entity_id, entity_type, action_type, new, old, logged_by, created_by, created_at
`

type CreateLogParams struct {
	EntityID   int32     `json:"entity_id"`
	EntityType string    `json:"entity_type"`
	ActionType string    `json:"action_type"`
	New        string    `json:"new"`
	Old        string    `json:"old"`
	LoggedBy   string    `json:"logged_by"`
	CreatedBy  int32     `json:"created_by"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLog,
		arg.EntityID,
		arg.EntityType,
		arg.ActionType,
		arg.New,
		arg.Old,
		arg.LoggedBy,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EntityType,
		&i.ActionType,
		&i.New,
		&i.Old,
		&i.LoggedBy,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listLogs = `-- name: ListLogs :many

SELECT id, entity_id, entity_type, action_type, new, old, logged_by, created_by, created_at FROM logs
WHERE entity_id = $1 AND entity_type = $2
ORDER BY created_at DESC
`

type ListLogsParams struct {
	EntityID   int32  `json:"entity_id"`
	EntityType string `json:"entity_type"`
}

// -- name: GetLog :one
// SELECT * FROM logs
// WHERE id = $1 LIMIT 1;
func (q *Queries) ListLogs(ctx context.Context, arg ListLogsParams) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, listLogs, arg.EntityID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.EntityType,
			&i.ActionType,
			&i.New,
			&i.Old,
			&i.LoggedBy,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
