insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Čukarica', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Novi Beograd', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Palilula', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Rakovica', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Savski Venac', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Stari grad', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Voždovac', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Zemun', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Zvezdara', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Barajevo', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Grocka', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Lazarevac', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Mladenovac', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Obrenovac', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Sopot', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Surčin', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Ostalo', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Novi Sad - Futog', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Novi Sad - Veternik', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Novi Sad - Begeč', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Novi Sad - Kisač', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Novi Sad - Rumenka', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Novi Sad - Stepanovićevo', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Novi Sad - Kać', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Novi Sad - Čenej', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Novi Sad - Budisava', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Novi Sad - Kovilj', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Novi Sad - Ostalo', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Niš - Medijana', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Niš - Palilula', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Niš - Pantelej', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Niš - Crveni krst', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Niš - Niška banja', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Niš - Ostalo', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Kragujevac - Aerodrom', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Kragujevac - Pivara', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Kragujevac - Stanovo', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Kragujevac - Stari grad', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Kragujevac - Stragari', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Kragujevac - Ostalo', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Subotica', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Zrenjanin', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Pančevo', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Čačak', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Novi Pazar', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Kraljevo', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Kruševac', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Jagodina', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Sremska Mitrovica', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Ruma', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Šabac', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Smederevo', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Bela crkva', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Kula', true, 0, current_timestamp, null, null);
insert into "Cities" ("Name", "IsActive", "CreatedBy", "CreatedAt", "UpdatedBy", "UpdatedAt") values ('Beograd - Resnik', true, 0, current_timestamp, null, null);