// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TD.Office.Common.Repository;

#nullable disable

namespace TD.Office.Common.DbMigrations.Migrations
{
    [DbContext(typeof(OfficeDbContext))]
    [Migration("20241108123945_UserMaxRabatAddedMigration")]
    partial class UserMaxRabatAddedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.KomercijalnoPriceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("NabavnaCenaBezPDV")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProdajnaCenaBezPDV")
                        .HasColumnType("numeric");

                    b.Property<int>("RobaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RobaId")
                        .IsUnique();

                    b.ToTable("KomercijalnoPrices");
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.LogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.NalogZaPrevozEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BrDok")
                        .HasColumnType("integer");

                    b.Property<decimal>("CenaPrevozaBezPdv")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MiNaplatiliKupcuBezPdv")
                        .HasColumnType("numeric");

                    b.Property<string>("Mobilni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<bool>("PlacenVirmanom")
                        .HasColumnType("boolean");

                    b.Property<string>("Prevoznik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("VrDok")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("NaloziZaPrevoz");
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.ProracunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("KomercijalnoBrDok")
                        .HasColumnType("integer");

                    b.Property<int?>("KomercijalnoVrDok")
                        .HasColumnType("integer");

                    b.Property<int>("MagacinId")
                        .HasColumnType("integer");

                    b.Property<int>("NUID")
                        .HasColumnType("integer");

                    b.Property<int?>("PPID")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Proracuni");
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.ProracunItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CenaBezPdv")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Pdv")
                        .HasColumnType("numeric");

                    b.Property<long>("ProracunId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Rabat")
                        .HasColumnType("numeric");

                    b.Property<int>("RobaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProracunId");

                    b.ToTable("ProracunItems");
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.SettingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.SpecifikacijaNovcaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Cekovi")
                        .HasColumnType("double precision");

                    b.Property<string>("CekoviKomentar")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp");

                    b.Property<int>("Eur1Komada")
                        .HasColumnType("integer");

                    b.Property<double>("Eur1Kurs")
                        .HasColumnType("double precision");

                    b.Property<int>("Eur2Komada")
                        .HasColumnType("integer");

                    b.Property<double>("Eur2Kurs")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double>("Kartice")
                        .HasColumnType("double precision");

                    b.Property<string>("KarticeKomentar")
                        .HasColumnType("text");

                    b.Property<string>("Komentar")
                        .HasColumnType("text");

                    b.Property<long>("MagacinId")
                        .HasColumnType("bigint");

                    b.Property<int>("Novcanica1000Komada")
                        .HasColumnType("integer");

                    b.Property<int>("Novcanica100Komada")
                        .HasColumnType("integer");

                    b.Property<int>("Novcanica10Komada")
                        .HasColumnType("integer");

                    b.Property<int>("Novcanica1Komada")
                        .HasColumnType("integer");

                    b.Property<int>("Novcanica2000Komada")
                        .HasColumnType("integer");

                    b.Property<int>("Novcanica200Komada")
                        .HasColumnType("integer");

                    b.Property<int>("Novcanica20Komada")
                        .HasColumnType("integer");

                    b.Property<int>("Novcanica2Komada")
                        .HasColumnType("integer");

                    b.Property<int>("Novcanica5000Komada")
                        .HasColumnType("integer");

                    b.Property<int>("Novcanica500Komada")
                        .HasColumnType("integer");

                    b.Property<int>("Novcanica50Komada")
                        .HasColumnType("integer");

                    b.Property<int>("Novcanica5Komada")
                        .HasColumnType("integer");

                    b.Property<double>("Papiri")
                        .HasColumnType("double precision");

                    b.Property<string>("PapiriKomentar")
                        .HasColumnType("text");

                    b.Property<double>("Sasa")
                        .HasColumnType("double precision");

                    b.Property<string>("SasaKomentar")
                        .HasColumnType("text");

                    b.Property<double>("Troskovi")
                        .HasColumnType("double precision");

                    b.Property<string>("TroskoviKomentar")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<double>("Vozaci")
                        .HasColumnType("double precision");

                    b.Property<string>("VozaciKomentar")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SpecifikacijaNovca", (string)null);
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MaxRabatMPDokumenti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(5m);

                    b.Property<decimal>("MaxRabatVPDokumenti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(5m);

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("VPMagacinId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.UserPermissionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Permission")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.UslovFormiranjaWebCeneEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Modifikator")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("WebProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UsloviFormiranjaWebcena");
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.ProracunEntity", b =>
                {
                    b.HasOne("TD.Office.Common.Contracts.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.ProracunItemEntity", b =>
                {
                    b.HasOne("TD.Office.Common.Contracts.Entities.ProracunEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("ProracunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.UserPermissionEntity", b =>
                {
                    b.HasOne("TD.Office.Common.Contracts.Entities.UserEntity", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.ProracunEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TD.Office.Common.Contracts.Entities.UserEntity", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
