namespace TD.Komercijalno.Contracts.Entities
{
    public class Partner
    {
        public int Ppid { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public string Posta { get; set; }
        public string Mesto { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Kontakt { get; set; }
        public decimal? Popust { get; set; }
        public short? VaziDana { get; set; }
        public short NeplFakt { get; set; }
        public decimal Duguje { get; set; }
        public decimal Potrazuje { get; set; }
        public short? VpcId { get; set; }
        public decimal? ProcPc { get; set; }
        public long? Kategorija { get; set; }
        public string Mbroj { get; set; }
        public string Sdel { get; set; }
        public int? Nppid { get; set; }
        public string MestoId { get; set; }
        public short? ImaUgovor { get; set; }
        public short? ImaIzjave { get; set; }
        public short? CenovnikId { get; set; }
        public string Rbroj { get; set; }
        public int? PristupniNivo { get; set; }
        public decimal NefakOtp { get; set; }
        public short? ZapId { get; set; }
        public short? VrstaCenovnika { get; set; }
        public short? PravnoLice { get; set; }
        public string DelatnostId { get; set; }
        public short? RefId { get; set; }
        public string Valuta { get; set; }
        public decimal? DozvoljeniMinus { get; set; }
        public string Pib { get; set; }
        public short? UvpcId { get; set; }
        public decimal? UprocPc { get; set; }
        public short? Pdvo { get; set; }
        public short? DrzavljanstvoId { get; set; }
        public short? ZanimanjeId { get; set; }
        public short? PrevozRobe { get; set; }
        public string WebKorisnik { get; set; }
        public short? WebStatus { get; set; }
        public short? DrzavaId { get; set; }
        public short? WebMagacinId { get; set; }
        public decimal? DugKupac { get; set; }
        public decimal? PotKupac { get; set; }
        public decimal? DugDobav { get; set; }
        public decimal? PotDobav { get; set; }
        public short? VpcRabat { get; set; }
        public short? WebDocConv { get; set; }
        public short? Aktivan { get; set; }
        public string NazivZaStampu { get; set; }
        public string Mobilni { get; set; }
        public long? WebPrivilegije { get; set; }
        public int? Gppid { get; set; }
        public short? CeneOdGrupe { get; set; }
        public short? Pol { get; set; }
        public short? WebDanaNeaktivan { get; set; }
        public short? WebNeaktivanStatus { get; set; }
        public short? Web { get; set; }
        public int? WebUserId { get; set; }
        public string WebShopUser { get; set; }
        public string WebShopPass { get; set; }
        public short? WebShopConv { get; set; }
        public short? OpstinaId { get; set; }
        public int? ReferId { get; set; }
        public DateTime? OdDatumWwebNeaktiv { get; set; }
        public string KontoTrosak { get; set; }
        public string KontoIzvod { get; set; }
        public short? WebStat { get; set; }
        public decimal? DozvoljeniMinusRok { get; set; }
        public int? LinijaId { get; set; }
        public decimal? ProcTro { get; set; }
        public short? VrstaUpita { get; set; }
        public short DevKl { get; set; }
        public int? Pgruid { get; set; }
        public short? Ekspid { get; set; }
        public short? SamoAvans { get; set; }
        public short? Zid { get; set; }
        public short? Sefid { get; set; }
        public short? Tkid { get; set; }
        public short? Promid { get; set; }
        public string Nadimak { get; set; }
        public string Gln { get; set; }
        public string NasGln { get; set; }
        public short? PrimaEf { get; set; }
        public short? Ef13 { get; set; }
        public short? Ef40 { get; set; }
        public short? Ef41 { get; set; }
    }
}
