namespace TD.Web.Common.Contracts.Enums;

public enum SettingKey
{
	FEATURE_CRON_AZURIRAJ_NIVO_NEAKTIVNIM_KORISNICIMA_ACTIVE,
	AZURIRAJ_NIVO_NEAKTIVNIM_KORISNICIMA_NEAKTIVAN_JE_AKO_NIJE_KUPOVAO_DANA,
	AZURIRAJ_NIVO_NEAKTIVNIM_KORISNICIMA_DESTINACIONI_NIVO,
	SMS_SEND_ZAKLJUCENA_PORUDZBINA,
	SMS_SEND_OBRADJENA_PORUDZBINA,
	CACHE_HASH,

	// AI Configuration
	AI_MODEL_NAME,
	AI_MAX_TOKENS,
	AI_TEMPERATURE,

	// AI Prompts - Product fields
	AI_PROMPT_PRODUCT_NAME_VALIDATION,
	AI_PROMPT_PRODUCT_DESCRIPTION_VALIDATION,
	AI_PROMPT_PRODUCT_SHORT_DESCRIPTION_VALIDATION,
	AI_PROMPT_PRODUCT_META_VALIDATION,
	AI_PROMPT_PRODUCT_DESCRIPTION_GENERATE,
	AI_PROMPT_PRODUCT_META_GENERATE,

	// AI Prompts - Blog fields (future)
	AI_PROMPT_BLOG_TITLE_VALIDATION,
	AI_PROMPT_BLOG_CONTENT_VALIDATION,
	AI_PROMPT_BLOG_CONTENT_GENERATE,
}
