namespace TD.Web.Common.Contracts.Enums;

public enum SettingKey
{
    FEATURE_CRON_AZURIRAJ_NIVO_NEAKTIVNIM_KORISNICIMA_ACTIVE,
    AZURIRAJ_NIVO_NEAKTIVNIM_KORISNICIMA_NEAKTIVAN_JE_AKO_NIJE_KUPOVAO_DANA,
    AZURIRAJ_NIVO_NEAKTIVNIM_KORISNICIMA_DESTINACIONI_NIVO
}
