const specificationEntity = {
    tableName: 'SpecifikacijeNovca',
    columns: {
        id: 'Id',
        storeId: 'MagacinId',
        isActive: 'IsActive',
        comment: 'Komentar',
        eur1Pieces: 'Eur1Komada',
        eur1ExchangeRate: 'Eur1Kurs',
        eur2Pieces: 'Eur2Komada',
        eur2ExchangeRate: 'Eur2Kurs',
        piecesOf5000: 'Novcanica_5000Komada',
        piecesOf2000: 'Novcanica_2000Komada',
        piecesOf1000: 'Novcanica_1000Komada',
        piecesOf500: 'Novcanica_500Komada',
        piecesOf200: 'Novcanica_200Komada',
        piecesOf100: 'Novcanica_100Komada',
        piecesOf50: 'Novcanica_50Komada',
        piecesOf20: 'Novcanica_20Komada',
        piecesOf10: 'Novcanica_10Komada',
        piecesOf5: 'Novcanica_5Komada',
        piecesOf2: 'Novcanica_2Komada',
        piecesOf1: 'Novcanica_1Komada',
        cards: 'Kartice',
        cardsComment: 'KarticeKomentar',
        cheques: 'Cekovi',
        chequesComment: 'CekoviKomentar',
        papers: 'Papiri',
        papersComment: 'PapiriKomentar',
        costs: 'Troskovi',
        costsComment: 'TroskoviKomentar',
        drivers: 'Vozaci',
        driversComment: 'VozaciKomentar',
        sasa: 'Sasa',
        sasaComment: 'SasaKomentar',
    },
}

module.exports = specificationEntity
